@piot_123_HostAddress = http://localhost:5253

POST {{piot_123_HostAddress}}/api/v2/check/
Content-Type: application/json
User-Agent: PostmanRuntime/7.51.1
Accept: */*
Cache-Control: no-cache
Postman-Token: c805d9e3-3508-4695-9e7d-aeaa1a18fc30
Host: localhost:5253
Accept-Encoding: gzip, deflate, br
Connection: keep-alive

[
  {
    "km": "00840147505712Zz;ZnRbAAAAdGVz",
    "priceTobaccoGroup": 15000
  }
]

###
